/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 3d-models-dreampalm.glb --transform 
Files: 3d-models-dreampalm.glb [62.77MB] > /home/arandadio/Dio Aranda/[0] Perkuliahan/Semester 7 dan 8/TA/Dio Aranda/0_Drone Tech/drone-tech-web-app/DreamPalm/project-drone/apps/client/public/models/3d-models-dreampalm-transformed.glb [3.25MB] (95%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/3d-models-dreampalm-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Tarot_650_Assembly.geometry} material={materials.PaletteMaterial001} position={[0.773, -19.424, -12.041]} rotation={[-0.008, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/3d-models-dreampalm-transformed.glb')
