import { z } from "zod";
import { prisma } from "../lib/prisma";
import { AppError, asyncHandler } from "../lib/http";

const updateDroneSchema = z.object({
  name: z.string().trim().min(1, "Nama perangkat tidak boleh kosong").optional(),
  isApproved: z.boolean().optional(),
});

export const listDrones = asyncHandler(async (req, res) => {
  const drones = await prisma.drone.findMany({
    include: {
      operator: {
        select: {
          id: true,
          name: true,
          email: true,
          status: true,
          emailVerified: true
        }
      }
    },
    orderBy: { createdAt: "desc" },
  });

  return res.status(200).json({
    success: true,
    data: drones,
  });
});

export const getDroneById = asyncHandler(async (req, res) => {
  const droneId = req.params.id as string;

  const drone = await prisma.drone.findUnique({
    where: { id: droneId },
    include: {
      operator: {
        select: {
          id: true,
          name: true,
          email: true,
          status: true,
          emailVerified: true,
        },
      },
    },
  });

  if (!drone) {
    throw new AppError(404, "Data drone tidak ditemukan.");
  }

  return res.status(200).json({
    success: true,
    data: {
      id: drone.id,
      name: drone.name,
      status: drone.status,
      isApproved: drone.isApproved,
      operator: drone.operator,
      linkFrequency: null,
    },
  });
});

export const updateDrone = asyncHandler(async (req, res) => {
  const droneId = req.params.id as string;
  const input = updateDroneSchema.parse(req.body);

  const existingDrone = await prisma.drone.findUnique({
    where: { id: droneId }
  });

  if (!existingDrone) {
    throw new AppError(404, "Data drone tidak ditemukan.");
  }

  const updatedDrone = await prisma.drone.update({
    where: { id: droneId },
    data: {
      name: input.name,
      isApproved: input.isApproved
    },
  });

  return res.status(200).json({
    success: true,
    message: "Data drone berhasil diperbarui.",
    data: updatedDrone,
  });
});

export const deleteDrone = asyncHandler(async (req, res) => {
  const droneId = req.params.id as string;

  const existingDrone = await prisma.drone.findUnique({
    where: { id: droneId },
    include: { operator: true }
  });

  console.log(existingDrone, 'exist');


  if (!existingDrone) {
    throw new AppError(404, "Data drone tidak ditemukan.");
  }

  if (existingDrone.operator.length > 0) {
    throw new AppError(
      400,
      `Drone tidak dapat dihapus karena masih di-assign ke pengguna 
      ${existingDrone.operator.map(op => op.name).join(", ")}. 
      Cabut assign terlebih dahulu di User Management.`
    );
  }

  await prisma.drone.delete({
    where: { id: droneId }
  });

  return res.status(200).json({
    success: true,
    message: "Data drone berhasil dihapus dari sistem."
  });
});


export const createDrone = asyncHandler(async (req, res) => {
  let autoGeneratedDroneId = null
  const existingDrones = await prisma.drone.findMany({
    where: { id: { startsWith: "v1-" } },
    select: { id: true }
  });

  // Ekstrak nomor urut dan urutkan dari terkecil ke terbesar
  const usedNumbers = existingDrones
    .map(drone => {
      const match = drone.id.match(/v1-(\d+)/);
      return match ? parseInt(match[1] || "0", 10) : 0;
    })
    .filter(n => n > 0)
    .sort((a, b) => a - b);

  // FIND gap pertama yang tersedia
  let nextSequence = 1;
  for (const num of usedNumbers) {
    if (num === nextSequence) {
      nextSequence++;
    } else if (num > nextSequence) {
      break;
    }
  }

  // Format menjadi 3 digit angka
  const seqStr = nextSequence.toString().padStart(3, "0");
  autoGeneratedDroneId = `v1-${seqStr}`;
  const droneName = `DreamPalm Drone V1-${seqStr}`;
  // const droneStatus = input.status === ApprovalStatus.APPROVED ? "Waiting Approval" : "Pending Approval";
  const droneStatus = "Pending Approval";
  console.log("log debug: nama drone", droneName);

  // Buat entri Drone baru secara otomatis
  const createdDrone = await prisma.drone.create({
    data: {
      id: autoGeneratedDroneId,
      name: droneName,
      status: droneStatus,
    }
  });

  return res.status(201).json({
    success: true,
    message: "Drone berhasil dibuat.",
    data: createdDrone,
  });
});